In [1]:
import numpy as np

In [2]:
my_array = np.array([ 10 , 12 , 14 , 16 , 20 , 25 ])
print (my_array)
print (my_array.dtype)
print (my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [24]:
string_array=np.array(["Red","Green","Blue"])
print(string_array)
print(string_array.dtype)
print(string_array.dtype.itemsize)


['Red' 'Green' 'Blue']
<U5
20


In [10]:
date_time_string_array=np.array(['1999-10-14','2001-03-14','2001-01-14'])
date_time_string_array.dtype

dtype('<U10')

In [17]:
# converting the date types
date_time_string_array=date_time_string_array.astype(dtype=np.datetime64)
date_time_string_array.dtype

dtype('<M8[D]')

In [19]:
# specify the array type
date_time_array=np.array(['1999-10-14','2001-03-14','2001-01-14'],dtype=np.datetime64)
date_time_array.dtype

dtype('<M8[D]')

In [20]:
# create an array from list
mylist=[1,2,3,4,5]
list_array=np.array(mylist)
list_array

array([1, 2, 3, 4, 5])

In [25]:
# create a mutly dimensional array from list of lists
# in this case a two-dimensional
mylist=[1,2,3,4,5]
mylist2=[6,7,8,9,10]
mylist3=[11,12,13,14,15]
ndarray=np.array([mylist,mylist2,mylist3])
print(ndarray)
print(ndarray.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [29]:
# creating an array in range of [0,5)
range_array=np.arange(start=0,stop=5)
print(range_array)
print(range_array.dtype)


[0 1 2 3 4]
int32


In [32]:
# creating an array in range of [-5,5)
# with step of 2 
# step means distance of each consecutive point in the array
range_array=np.arange(start=-5,stop=5,step=2)
print(range_array)


[-5 -3 -1  1  3]


In [39]:
#  make an array of size 5
# that every elemnt is equal to 1
ones_array=np.ones(shape=5)
print(ones_array)
print(ones_array.dtype)


[1. 1. 1. 1. 1.]
float64


In [40]:
#  make a two dimensional ones-array 
# which has 2 rows and 3 comlumns
# and type of int32
ones_array=np.ones(shape=[2,3],dtype=np.int32)
print(ones_array)
print(ones_array.dtype)


[[1 1 1]
 [1 1 1]]
int32


In [41]:
# create a zeros array with 1 row and 3 coolumns 
zero_array=np.zeros(3)
print(zero_array)


[0. 0. 0.]


In [42]:
# create a zeros array with 3 rows and 4 coolumns 
zero_array=np.zeros([3,4])
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
# using the Eye to create an identity matrix with 4 rows and columns 
identity_array=np.eye(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
# using the Eye to create an identity matrix with 2 rows and 3 columns
# I =[1,0,0
#     0,1,0]
identity_array=np.eye(2,3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]]


In [56]:
# Creating random array which has float numbers as elements
# the parameters are dimensions of the array 
# in this case we have a two-dimensional array 
# with 1 row and 3 columns
random_array=np.random.rand(1,3) 
print(random_array)


[[0.16373658 0.91582565 0.86765818]]
[2 1 1 1 5]


In [69]:
# randint method makes an int array 
# in range of [low , high) and the specific size 
random_int_array=np.random.randint(low=1,high=10,size=5)
print(random_int_array)


[8 4 7 2 1]


In [70]:
# randn return  a normal random array with the specified sizes 
random_array_randn=np.random.randn(2,1)
print(random_array_randn)


[[ 0.32343461]
 [-0.20059049]]


In [78]:
# Some arrays attributes
sample_array=np.array([[1,2,3],[4,5,6]])
print("Dimension of the array:{}".format(sample_array.ndim))
print("Shape of the array:{}".format(sample_array.shape))
print("Data Type of the array:{}".format(sample_array.dtype))
print("Size of the Elements in array: {}".format(sample_array.itemsize))



Dimension of the array:2
Shape of the array:(2, 3)
Data Type of the array:int32
Size of the Elements in array: 4


In [89]:
# some ways two iteration over an array
iteration_array=np.array([[1,2,3],[4,5,6]])
# nested for
print('First way of iteration:')
for rows in iteration_array:
    for each_column in rows :
        print(each_column)

# flat attr
# flat attribute make a sample 1-d array from the main array
# then iterate over it
print('Second way of iteration:')
print(* iteration_array.flat  ,sep="\n")


First way of iteration:
1
2
3
4
5
6
Second way of iteration:
1
2
3
4
5
6


In [90]:
# add an element to array by
# append 
Colors_arry=np.array(['red','green','blue'])
print('Color array before adding white :\n',Colors_arry)
Colors_arry=np.append(Colors_arry,'white')
print('Color array after adding :\n',Colors_arry)


Color array before adding white :
 ['red' 'green' 'blue']
Color array after adding :
 ['red' 'green' 'blue' 'white']


In [91]:
# appending more than one element 
Colors_arry=np.array(['red','green','blue'])
print('Color array before  :\n',Colors_arry)
Colors_arry=np.append(Colors_arry,['white','black'])
print('Color array after adding :\n',Colors_arry)


Color array before  :
 ['red' 'green' 'blue']
Color array after adding :
 ['red' 'green' 'blue' 'white' 'black']


In [92]:
# appending elements with different data types 
Colors_arry=np.array(['red','green','blue'])
print('Color array before  :\n',Colors_arry)
Colors_arry=np.append(Colors_arry,[255,0])
print('Color array after adding :\n',Colors_arry)


Color array before  :
 ['red' 'green' 'blue']
Color array after adding :
 ['red' 'green' 'blue' '255' '0']


In [113]:
# appending elements to a 2d array 
# in this case we are adding to the rows
# axis=0
Colors_arry=np.array([['red','green'],['blue','gray']])
print('Color array before  :\n',Colors_arry)
Colors_arry=np.append(Colors_arry,[['black','white']],axis=0)
print('Color array after  :\n',Colors_arry)
# note that in this example the number of the columns in both array must be the same


Color array before  :
 [['red' 'green']
 ['blue' 'gray']]
Color array after adding :
 [['red' 'green']
 ['blue' 'gray']
 ['black' 'white']]


In [117]:
# appending elements to a 2d array 
# in this case we are adding to the columns
# axis=1
Colors_arry=np.array([['red','green'],['blue','gray']])
print('Color array before  :\n',Colors_arry)
Colors_arry=np.append(Colors_arry,[['black'],['white']],axis=1)
print('Color array after  :\n',Colors_arry)

# note that in this example the number of the rows in both array must be the same


Color array before  :
 [['red' 'green']
 ['blue' 'gray']]
Color array after  :
 [['red' 'green' 'black']
 ['blue' 'gray' 'white']]


In [126]:
# Removing elements from array by delete
# the first parameter is the array 
# the second one is the indexes of the elements

# delete one index 
sample_array=np.array([1,2,3,4,5])
print('Origin array: ',sample_array)
deleted_array=np.delete(sample_array,2)
print('Array after deletion: ',deleted_array)





Origin array:  [1 2 3 4 5]
Array after deletion:  [1 2 4 5]


In [127]:
# delete multiple indexes
sample_array=np.array([6,7,8,9,10])
print('Origin array: ',sample_array) 
deleted_array=np.delete(sample_array,[0,1,2])
print('Array after deletion: ',deleted_array)


Origin array:  [ 6  7  8  9 10]
Array after deletion:  [ 9 10]


In [132]:
# delete from 2d-array
# axis=0 means delete row
sample_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Origin array: \n',sample_array) 
deleted_array=np.delete(sample_array,0,axis=0)
print('Array after deletion: \n',deleted_array)



Origin array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after deletion: 
 [[4 5 6]
 [7 8 9]]


In [134]:
# delete from 2d-array
# axis=1 means delete column
sample_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Origin array: \n',sample_array) 
deleted_array=np.delete(sample_array,2,axis=1)
print('Array after deletion: \n',deleted_array)



Origin array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after deletion: 
 [[1 2]
 [4 5]
 [7 8]]
